env variables and secrets

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -100,6 +100,8 @@ jobs:
 
     runs-on: ubuntu-latest
 
+    enviroment: production
+
     steps:
       - name: Download deployed artifacts
         uses: actions/download-artifact@v5
@@ -110,8 +112,24 @@ jobs:
       - name: Show deployment files
         run: ls -la deployment-package
 
+      - name: Show deployment enviroment
+        run: echo "Deplpying to ${{ vars.DEPLOY_ENV }}"
+
+      - name: Verify Secrets Exists
+        env:
+          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
+
+        run: |
+          if [-z "$DEPLOY_TOKEN"]; then
+            echo "credential is missing"
+            exit 1
+          fi
+
+          echo "credential is available"
+        
+
       - name: Simulate deployment
-        run: echo "Deploying the validated artifact"
+        run: echo "Deploying the validated artifact to production"
 
 
 
